---
title: "The microbial ecological dynamics of nitrogen loss versus retention"
author: "Manuscript by J Fadum, X SUn, and E Zakem. R Code by J Fadum"
date: "2024-09-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This code relies on outputs from the python code included in this folder. If running analysis from scratch, begin with python code. Data files used to produce figures in Fadum et al. are included in folder as well, in which case running the python code is not required for the below analysis. 

```{r echo = TRUE, error=FALSE, eval=TRUE, include=FALSE, message=FALSE, warning=FALSE}
## Required Packages

library(readr) #imports csv files
library(tidyverse) #for data transformation
library(ggplot2) # for data viz
library(ggthemes) # for figure aesthetics
library(geomtextpath) # for figure aesthetics

setwd("~/Fadum_etal_2025_DNRAvDenit")

```

```{r echo = TRUE, error=FALSE, eval=TRUE, include=TRUE, message=FALSE, warning=FALSE}
## Model parameters, yields, and R* calcs

#All Functional Types
L= 0.04 #Loss rate (referred to as 'Dilution' in text)
K_om = 1 #Have saturation constant of organic matter (uM-N)
K_n = 0.1 #Have saturation constant of inorganic N (uM-N)
Vmax_OM= 3 #Estimate of mol OM-N consumered per mol Biomass-N per day 
Vmax_N= 30 #Estimate of mol inorganic N consumered per mol Biomass-N per day 


#Full range of yields provided in Table 1 of text. Below values reflect a baseline assumption of 0.25 mols biomass per mol N of oxidized OM. See text for details
#e= excretion in mol resource-N per mol biomass

#DNRA (NO2 -> NH4)
Y_om_dnra=0.15411277631242076
Y_no2_dnra= 0.035540231352775384
e_nh4_dnra= 33.625881599896815

#Denit step 1 (NO2 ->N2O)
Y_om_denit_n2o= 0.25112773484637685
Y_no2_denit= 0.020859998366548553
e_n2o_denit= 47.93864229652179 

#Denit step 2 (N2O ->N2)
Y_om_denit_n2= 0.35101407125328626
Y_n2o_denit= 0.015897579041237  
e_n2_denit= 62.90265941789521 

#Full Denit (NO2 -> N2)
Y_om_fulldenit= 0.2863727184228211
Y_no2_fulldenit= 0.03675757740778556
e_n2_full_denit= 27.205274953408427 

#Anammox (NO2 + NH4 -> N2)
Y_no2_ana= 0.01123596
Y_nh4_ana= 0.013333333333333334
e_n2_ana= 150


#Consumption vectors
#Resource CVs for DNRA ((− • − • −) and Full Denit (----) displayed in Figure 3. 
R_dnra= Y_no2_dnra/Y_om_dnra #CV for DNRA
R_denit_n2o= Y_no2_denit/Y_om_denit_n2o #CV for Denit step 1
R_denit_n2= Y_n2o_denit/Y_om_denit_n2 #CV for Denit step 2
R_FullDenit= Y_no2_fulldenit/Y_om_fulldenit #CV for non-modular denitrification 
R_ana= Y_no2_ana/Y_nh4_ana #CV for anammox

#Avg (coexist)
coex= (R_dnra+R_FullDenit)/2 #Same as Net Zero N Loss. Calculated here to double check CVs 

#R*s
#R*s represent the minimum resource requirement of a given functional type
#OM*s
OM_dnra= (K_om*L)/(Y_om_dnra*Vmax_OM-L)
OM_denit_n2o= (K_om*L)/(Y_om_denit_n2o*Vmax_OM-L)
OM_denit_n2= (K_om*L)/(Y_om_denit_n2*Vmax_OM-L)
OM_FullDenit= (K_om*L)/(Y_om_fulldenit*Vmax_OM-L)

#NO2*s
NO2_dnra= (K_n*L)/(Y_no2_dnra*Vmax_N-L)
NO2_denit= (K_n*L)/(Y_no2_denit*Vmax_N-L)
NO2_ana= (K_n*L)/(Y_no2_ana*Vmax_N-L)
NO2_FullDenit= (K_n*L)/(Y_no2_fulldenit*Vmax_N-L)

#NH4*s
NH4_ana= (K_n*L)/(Y_nh4_ana*Vmax_N-L)

#Because CVs do not pass through the origin, b (as in y=mx+b) is calculated to provide correction on Figure 4
b_dnra = OM_dnra - (R_dnra*NO2_FullDenit)
b_denit= OM_FullDenit - (R_FullDenit*NO2_FullDenit)

#Net zero N loss

NZNL= .5*((Y_no2_fulldenit/Y_om_fulldenit)+(Y_no2_dnra/Y_om_dnra))

```

```{r echo = TRUE, error=FALSE, eval=TRUE, include=TRUE, message=FALSE, warning=FALSE}
## Load model outputs and calculate rates

#.py files export without OM and nitrite values so here we add them back in...
#update according to model run in python. for the example files, NO2 supply rate was held constant at 25 uM N/m^3/day and OM varies from 0 to 10 in increments of 0.01 uM N/m^3/day.
row_names=seq(0,10, by=0.01) #OM 

##Biomass
b_DNRA <- read.csv("~/Fadum_etal_2025_DNRAvDenit/python/DNRA_biomass_Fig4.csv", header=F) #import .py output
row.names(b_DNRA)=row_names #Add OM supply rates in rows 
colnames(b_DNRA)="DNRA" #Provide column name for when functional types are combined 

#Denit (NO2 -> N2O) 
b_denit1=read.csv("~/Fadum_etal_2025_DNRAvDenit/python/IncompDenit_biomass_Fig4.csv", header=F)  #import .py output
row.names(b_denit1)=row_names #Add OM supply rates in rows 
colnames(b_denit1)="Denit_Step1" #Provide column name for when functional types are combined

#Denit (N2O -> N2) 
b_denit2=read.csv("~/Fadum_etal_2025_DNRAvDenit/python/CompDenit_biomass_Fig4.csv", header=F) #import .py output
row.names(b_denit2)=row_names #Add OM supply rates in rows 
colnames(b_denit2)="Denit_Step2" #Provide column name for when functional types are combined

#Denit- combined biomasses
b_fulldenit= b_denit1 + b_denit2

#Anammox heatmapAna
b_ana =read.csv("~/Fadum_etal_2025_DNRAvDenit/python/Anammox_biomass_Fig4.csv", header=F)  #import .py output
row.names(b_ana)=row_names #Add OM supply rates in rows 
colnames(b_ana)="Anammox" #Provide column name for when functional types are combined

##Geochem

#NO2 remaining
fin_NO2=read.csv("~/Fadum_etal_2025_DNRAvDenit/python/fin_NO2_Fig4.csv", header=F)  #import .py output
row.names(fin_NO2)=row_names #Add OM supply rates in rows 
colnames(fin_NO2)="NO2_remaining" #Provide column name for when functional types are combined

#OM remaining
fin_OM=read.csv("~/Fadum_etal_2025_DNRAvDenit/python/fin_OM_Fig4.csv", header=F)  #import .py output
row.names(fin_OM)=row_names #Add OM supply rates in rows
colnames(fin_OM)="OM_remaining" #Provide column name for when functional types are combined

#NH4 remaining
fin_NH4=read.csv("~/Fadum_etal_2025_DNRAvDenit/python/fin_NH4_Fig4.csv", header=F)  #import .py output
row.names(fin_NH4)=row_names #Add OM supply rates in rows
colnames(fin_NH4)="NH4_remaining" #Provide column name for when functional types are combined

##Calculating uptake and production rates
# DNRA
DNRA_NO2 = ((b_DNRA*L)/Y_no2_dnra) # calculate NO2 uptake rate
DNRA_NO2 = as.matrix(DNRA_NO2) # convert to matrix for data viz

DNRA_NH4 = (b_DNRA*L)*(1/Y_no2_dnra) # calculate NH4 production 
DNRA_NH4 = as.matrix(DNRA_NH4) # convert to matrix for data viz

DNRA_NH4_ex = (b_DNRA*L*e_nh4_dnra)  # calculate total NH4 production from OM
DNRA_NH4_ex = as.matrix(DNRA_NH4_ex) # convert to matrix for data viz

#Denit step 1
Denit_NO2 = ((b_denit1*L)/Y_no2_denit) # calculate NO2 uptake rate
Denit_NO2 = as.matrix(Denit_NO2) # convert to matrix for data viz

Denit_NH4_A = (b_denit1*L* (1/Y_om_denit_n2o - 1)) # calculate NH4 prod rate
Denit_NH4_A = as.matrix(Denit_NH4_A) # convert to matrix for data viz

#Denit step 2
Denit_N2O = ((b_denit2*L)/Y_n2o_denit) # calculate N2O uptake rate
Denit_N2O = as.matrix(Denit_N2O) # convert to matrix for data viz

Denit_NH4_B = (b_denit2*L* (1/Y_om_denit_n2 - 1)) # calculate NH4 production rate
Denit_NH4_B = as.matrix(Denit_NH4_B) # convert to matrix for data viz

Denit_N2 = (b_denit2*L*e_n2_denit) # calculate N2 production rate
Denit_N2 = as.matrix(Denit_N2) # convert to matrix for data viz

# Anammox
Anammox_NH4 = (b_ana*L/ Y_nh4_ana) # calculate NH4 uptake rate
Anammox_NH4 = as.matrix(Anammox_NH4) # convert to matrix for data viz

Anammox_NO2 = ((b_ana*L)/Y_no2_ana) # calculate NO2 uptake rate 
Anammox_NO2 = as.matrix(Anammox_NO2 ) # convert to matrix for data viz

Anammox_N2_op = (b_ana*L)*(1/Y_no2_ana) #N2 just from NO2
Anammox_N2_op = as.matrix(Anammox_N2_op) # convert to matrix for data viz
Anammox_N2 = (b_ana*L*e_n2_ana) # calculate total N2 production rate
Anammox_N2 = as.matrix(Anammox_N2) # convert to matrix for data viz


#Ranges for data viz (keep NO2 the same and vary OM)
OM_supply = seq(0.0,10, by=.01) # create OM supply rate sequence (full length)
NO2_supply = rep(c(25), times=length(OM_supply)) # Fill in NO2 supply


```


```{r echo = TRUE, error=FALSE, eval=TRUE, include=FALSE, message=FALSE, warning=FALSE}
## Create larger consolidated dataframe

Full_df<- cbind(NO2_supply,OM_supply,b_DNRA,b_denit1,b_denit2, b_ana,
                fin_NH4,fin_NO2,fin_OM) %>% 
  mutate(Ratio= OM_supply/NO2_supply, 
         Denit= Denit_Step1 + Denit_Step2) %>% 
  select(!NO2_supply, OM_supply) %>% 
  pivot_longer(!Ratio, names_to = "Name", values_to = "value")  %>% 
   filter(Ratio<0.25,
         Ratio>0) 


```

## Figure 4 Panels 

```{r echo = FALSE, error=FALSE, eval=TRUE, include=TRUE, message=FALSE, warning=FALSE, fig.width=10, fig.height=3, fig.align='center'}
#Figure 4A: Biomass comparison 

biomassplot<- Full_df %>% 
filter(Name == "DNRA" |
      Name == "Anammox" |
      Name == "Denit_Step1" |
      Name == "Denit"
      ) %>% 
  ggplot(aes(x=Ratio, y=value, group=Name, color= Name)) +
  geom_line(size=6)+
  theme_few()+
  scale_y_continuous(name = "Biomass")+
  theme(legend.position="none")+
  scale_color_manual(values=c("orange", "#50c5b7", "#50c5b7", "#EF476F"))+
  geom_vline(xintercept= NZNL, linetype="dotted", color = "black", alpha=0.5, size=5)+
  geom_vline(xintercept=(R_dnra+(b_dnra/25)), linetype="dashed", color= "#EF476F", alpha=0.5, size =5)+ 
  geom_vline(xintercept=0.1312, linetype="dashed", color= "#50c5b7", alpha=0.5, size=5)

biomassplot

#ggsave("Fig4A_raw.png", plot = biomassplot, width = 42, height = 8, units = "in", dpi= 600)


```


```{r echo = TRUE, error=FALSE, eval=TRUE, include=FALSE, message=FALSE, warning=FALSE}
## Figure 4B: Relative NO2 uptake

Comp= cbind(NO2_supply, OM_supply) # combine created vectors
Comp= as.data.frame(Comp)%>% 
  mutate(Ratio = OM_supply/NO2_supply) # calculate supply rate ratio

Comp= cbind(Comp, DNRA_NO2, Denit_NO2, Anammox_NO2) # combine extracted values

Comp<-Comp %>% 
  mutate(percent_Ana= (Anammox_NO2/ (DNRA_NO2+Denit_NO2+Anammox_NO2))*100,
         percent_Denit= (Denit_NO2/ (DNRA_NO2+Denit_NO2+Anammox_NO2))*100,
         percent_DNRA= (DNRA_NO2/ (DNRA_NO2+Denit_NO2+Anammox_NO2))*100) %>% 
  select(Ratio, percent_Ana, percent_Denit, percent_DNRA) %>%   # trim down data set
  pivot_longer(!c(Ratio), names_to = "metabolism", values_to = "rate") %>% 
  filter(Ratio<0.25,
         Ratio>0) 


comp_plot<- ggplot(Comp, aes(fill=metabolism, y=rate, x=Ratio)) +
  geom_bar(width=0.005,position="stack", stat="identity")+
  scale_fill_discrete(name = "Metabolisms", labels = c("Anammox", "Denitrification", "DNRA"))+
  theme_few()+
  ggtitle ("Nitrite reduction rate comparison")+
  ylab("Relative rate (% of NO2 reduction) ")+
  xlab("OM:NO2 supply rate") +
    theme(legend.position="none")+
   geom_vline(xintercept=NZNL, linetype="dotted", color = "black", alpha=0.5, size=5)+

  scale_fill_manual(values= c("orange", "#50c5b7", "#EF476F"))

comp_plot

#ggsave("Fig4B_raw.png", plot = comp_plot, width = 42, height = 8, units = "in", dpi= 600)

```



```{r echo = TRUE, error=FALSE, eval=TRUE, include=FALSE, message=FALSE, warning=FALSE}

## Figure 4C: Loss versus retention

df= cbind(NO2_supply, OM_supply) # combine created vectors
df= as.data.frame(df)%>% 
  mutate(Ratio = OM_supply/NO2_supply) # calculate supply rate ratio


Balance= cbind(df, DNRA_NH4_ex, Denit_N2, Anammox_N2_op)  %>% 
  mutate(retention= ifelse(DNRA < 0.00001, 0, DNRA),
         loss = (Denit_Step2 + Anammox)*-1,
         Denit_N2 = Denit_Step2*-1,
         Anammox= Anammox *-1,
         net = retention + loss) %>% 
  select(Ratio, retention, Denit_N2, Anammox, net)  %>% 
  pivot_longer(!c(Ratio, net), names_to = "category", values_to = "value") %>%  
  filter(Ratio<.25)
  


Balance_plot<- ggplot(Balance) +
  aes(x = Ratio, fill = category, weight = value, by = 1) + #base plot
  geom_bar(width=0.005) +
  ggtitle("Net Nitrogen Loss and Retention")+ #add title
  xlab("OM:NO2 supply rate")+ #add x axis label
  ylab("mols N") + #add y axis label
  geom_line(data = Balance, aes(x = Ratio , y = net), size = 6, color = "black")+
  theme_few()+
  theme(legend.position="none")+
  scale_fill_manual(values= c("orange", "#50c5b7", "#EF476F"),
                     name = "Inorganic N", labels = c("N2 loss from Anammox", "N2 loss from Denitrification", "NH4 produced by DNRA")) +
  geom_vline(xintercept=NZNL, linetype="dotted", color = "black", size=6.5)+
  scale_y_continuous(
    # Features of the first axis
    name = "Flux (umols N/m3/day)")

Balance_plot

#ggsave("Fig4C_raw.png", plot = Balance_plot, width = 42, height = 16, units = "in", dpi= 600)

```

## Supp Figures

```{r echo = FALSE, error=FALSE, eval=TRUE, include=TRUE, message=FALSE, warning=FALSE, fig.width=10, fig.height=3, fig.align='center'}

## Figure S1: Percent N2 from anammox

Percent= cbind(df, Denit_N2, Anammox_N2) %>% 
  mutate(Denit_N2= ifelse(Denit_N2 < 0.00000001, 0, Denit_N2),
         Anammox= ifelse(Anammox < 0.00000001, 0, Anammox),
         perc_ana= (Anammox/(Anammox+Denit_N2))*100) %>% 
  select(Ratio, perc_ana)  %>%  
  filter(Ratio<.25) %>% 
  drop_na()

Percent_plot<- ggplot(Percent) +
  aes(x = Ratio, y= perc_ana) + #base plot
  geom_line(size=3) +
  theme_few()+
  ggtitle("Anammox contribution to N2")+ #add title
  xlab("OM:NO2 supply rate")+ #add x axis label
  ylab(" Percentage of N2 produced by Anammox") + #add y axis label
  geom_hline(yintercept=28, linetype="dashed", color = "black", size=2, alpha=0.5)


Percent_plot

#ggsave("FigS1_raw.png", plot = Percent_plot, width = 42, height = 8, units = "in", dpi= 600)
```


```{r echo = FALSE, error=FALSE, eval=TRUE, include=TRUE, message=FALSE, warning=FALSE, fig.width=10, fig.height=3, fig.align='center'}

## Figure S4B: Inorganic N accumulation

InorgN<- Full_df %>% 
filter(Name == "NH4_remaining" |
      Name == "NO2_remaining" 
      ) %>% 
  ggplot(aes(x=Ratio, y=value, group=Name, color= Name)) +
  geom_line(size=6)+
  geom_area(aes(fill=Name)) +
  theme_few()+
  scale_y_continuous(name = "Inorganic N accumulation")+
  theme(legend.position="none")+
  scale_color_manual(values=c("#802392", "#4B3F72"))+
  scale_fill_manual(values=c("#802392", "#4B3F72"))+
  geom_vline(xintercept= NZNL, linetype="dotted", color = "black", alpha=0.5, size=5)

InorgN

#ggsave("FigS4B_raw.png", plot = InorgN, width = 42, height = 8, units = "in", dpi= 600)
```

```{r echo = FALSE, error=FALSE, eval=TRUE, include=TRUE, message=FALSE, warning=FALSE, fig.width=10, fig.height=3, fig.align='center'}

## Figure S6: (Not included in final version of manuscript, used to check OM* values)

OM_check<- Full_df %>% 
filter(Name == "OM_supply"|
       Name == "OM_remaining")  %>%  
  pivot_wider(names_from = Name, values_from = value) %>% 
  select(!Ratio) %>% 
  #pivot_longer(!OM_supply, names_to = "Name", values_to = "value") 
  ggplot(aes(x=OM_supply, y=OM_remaining)) +
  geom_line(size=6)+
  theme_few()+
  xlab( "OM loading")+
  ylab("OM remaining in chemostat")+
  geom_hline(yintercept= OM_dnra, linetype="dashed", color= "#EF476F", alpha =0.5, size=5)+
  geom_hline(yintercept= OM_denit_n2o, linetype="dashed", color= "#50c5b7", alpha= 0.5, size=5)
  #annotate("text", x= 6.5, y= OM_dnra-0.005, label= "OM* DNRA", size=3, color= "red")  +
  #annotate("text", x= 2.7, y= OM_denit_n2o-0.005, label= "OM* Denit (NO2 to N2O)", size= 3, color= "blue")

OM_check

#ggsave("FigS5_raw.png", plot = OM_check, width = 42, height = 8, units = "in", dpi= 600)


```
